### ISSUE TITLE
styling issue

### ISSUE THREAD

**Issue by Tony-Stark-Jr** [sersavan/shadcn-multi-select-component#1]
First, thanks you.
As we need to style component according to own design. I am unable to customize style of this compoent.
Here is my code,
```
 <FormField
            control={form.control}
            name="sizes"
            render={({ field }) => (
              <FormItem>
                {/* <FormLabel>Select size</FormLabel> */}
                <FormControl>
                  <MultiSelectFormField
                    options={sizesList}
                    defaultValue={field.value}
                    onValueChange={field.onChange}
                    placeholder="Select sizes"
                    className="h-30 max-w-[300px] shadow-none"
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
```
          Please help me to customize this component

**Comment by sersavan** [comment]
@Tony-Stark-Jr 

Hi, I've added a few props, including `className` and `variant`, as in the native shadcn/ui.
Now you can control the style of the component yourself.
Preset variants: `default`, `secondary`, `destructive`, `inverted`.
The animation is enabled by adding a prop `animation` in which you set the animation speed (less -> faster), along with it a `magic wand` appears so that the user can always turn it off.

<img width="1025" alt="image" src="https://github.com/sersavan/shadcn-multi-select-component/assets/3727722/68bfac25-adf9-458b-b343-d174f9eefad8">
